version: '3'

services:
  mysql:
    image: mysql
    ports:
      - $MYSQL_PORT:3306
    environment: &environment
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
      MYSQL_ALLOW_EMPTY_PASSWORD: 1

  php:
    image: ngyuki/php-dev:7.0-alpine
    volumes:
      - ./:/app/
    working_dir: /app/
    environment:
      <<: *environment
    command:
      - sh
      - -c
      - |
        composer install -o --ansi --prefer-dist
        php -v
        tail -f /dev/null
