version: '3.4'

services:
  mysql:
    image: mysql:5.7
    ports:
      - ${MYSQL_TCP_PORT-13306}:3306
    environment: &environment
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_DATABASE: ${MYSQL_DATABASE-test}
      MYSQL_USER: ${MYSQL_USER-test}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD-pass}
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    command:
      - --character-set-server=utf8

  php:
    image: ngyuki/php-dev:${PHP_VERSION:-7.0}
    init: true
    user: ${DOCKER_USER:-0}
    depends_on:
      - mysql
    volumes:
      - ./:/app/
    working_dir: /app/
    environment: *environment
    command:
      - sh
      - -c
      - |
        composer install -o --ansi --prefer-dist
        php -v
        echo
        exec tail -f /dev/null
